### ISSUE TITLE
Geometry not in output

### ISSUE THREAD

**Issue by shauncopley** [apfister/SDMXExplorer#1]
I have tested the SDMXExplorer tool using the ABS Beta provider - tool successfully generates a dataset (table), but does not appear to output with a geometry. Tested with several dataflows, including 'ABS_REGIONAL_ASGS2016] - Regional Statistics, ASGS 2016, 2011-2018.

Geography has been set to SA2 and boundaries loaded into ArcGIS Pro with join parametres set.

**Comment by apfister** [comment]
@shauncopley can use the "Copy URL" and paste it in here so i can test with what you are using exactly? also, can you grab a screenshot of the panel and let me know what Geography layer you are using? thanks!

**Comment by shauncopley** [comment]
@apfister here is an example URL I have tested : https://api.data.abs.gov.au/data/ABS,ABS_REGIONAL_ASGS2016,1.0.0/INCOME_17.SA2...?&detail=full&dimensionAtObservation=TIME_PERIOD

Geography is SA2 - when running 'create layer' it does produce a feature layer with the correct attributes, but it doesn't appear to have any geometry related to it. The polygons in the screenshot is the 'input' geography.

![image](https://user-images.githubusercontent.com/77363018/111923255-299df780-8aee-11eb-9adb-92773737c7df.png)

**Comment by apfister** [comment]
@shauncopley it looks like you have the Region Type dimension set as your geography. I think it was the Region dimension that works with the join. Can you switch to the Region tab and click Set as Geography and then create layer again?

**Comment by apfister** [comment]
@shauncopley were you able to track this one down?
